# Generated by Django 2.1.5 on 2019-01-31 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakenItem',
            fields=[
                ('itemBeingBroughtID', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('comment', models.TextField(default='')),
            ],
        ),
        migrations.RenameField(
            model_name='attendee',
            old_name='RSVP',
            new_name='RSVPStatus',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='itemID',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='userattendeeID',
        ),
        migrations.AddField(
            model_name='attendee',
            name='attendeeName',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='attendee',
            name='userAttendeeID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='eventCategory',
            field=models.IntegerField(blank=True, choices=[(0, 'Misc'), (1, 'Party'), (2, 'Education'), (3, 'Music'), (4, 'Food and Drink'), (5, 'Movies'), (6, 'Arts'), (7, 'Technology'), (8, 'Health'), (9, 'Out Doors'), (10, 'Sports')], null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='amountTaken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profilePhoto',
            field=models.ImageField(blank=True, default=None, upload_to='profile_photos'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='attendeeID',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='eventID',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='main_app.EventInfo'),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='eventPhoto',
            field=models.ImageField(blank=True, default=None, upload_to='event_photos', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='id',
            field=models.CharField(default='', max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='userProfile',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='main_app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='item',
            name='eventID',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='main_app.EventInfo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete='CASCADE', related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='takenitem',
            name='attendeeID',
            field=models.ForeignKey(on_delete='CASCADE', to='main_app.Attendee'),
        ),
        migrations.AddField(
            model_name='takenitem',
            name='eventID',
            field=models.ForeignKey(on_delete='CASCADE', to='main_app.EventInfo'),
        ),
        migrations.AddField(
            model_name='takenitem',
            name='itemLinkID',
            field=models.ForeignKey(on_delete='CASCADE', to='main_app.Item'),
        ),
    ]
